# -*- coding: utf-8 -*-
"""ExoPlanetHabitabilityPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dng31lS-eT0j7BffU7Do0GJeO1CJq9z_
"""

!ls

"""Load Dataset and cleaning"""

import pandas as pd

df = pd.read_csv("exoplanet_full_dataset.csv", comment="#")
print(df.shape)
df.head()

df.isnull().sum()

df.isnull().sum().sort_values(ascending=False).head(20)

df = df.dropna(axis=1, how="all")
print(df.shape)

df = df.drop_duplicates()
print(df.shape)

df.columns

selected_cols = [
    "pl_rade",    # Planet radius
    "pl_bmasse",  # Planet mass
    "pl_orbper",  # Orbital period
    "pl_eqt",     # Equilibrium temperature
    "st_teff",    # Star temperature
    "st_mass",    # Star mass
    "st_rad",     # Star radius
    "sy_dist",    # System distance
    "pl_insol",   # Planet insolation flux
    "st_met"      # Star metallicity
]

df_selected = df[selected_cols]
df_selected.head()

df_selected = df_selected.fillna(df_selected.median(numeric_only=True))
df_selected.isnull().sum()

X = df[selected_cols].fillna(df[selected_cols].median())

y = ((df["pl_rade"] >= 0.5) & (df["pl_rade"] <= 2.0) &
     (df["pl_eqt"] >= 180) & (df["pl_eqt"] <= 310)).astype(int)

print(df["pl_rade"].min(), df["pl_rade"].max())
print(df["pl_eqt"].min(), df["pl_eqt"].max())

y = ((df["pl_rade"] >= 0.5) & (df["pl_rade"] <= 2.5) &  # slightly bigger upper radius
     (df["pl_eqt"] >= 150) & (df["pl_eqt"] <= 400)).astype(int)

print(y.value_counts())

df_selected.to_csv("clean_exoplanet_dataset.csv", index=False)
print("Dataset cleaned and saved!")

df_selected["habitable"] = (
    (df_selected["pl_rade"] >= 0.5) & (df_selected["pl_rade"] <= 2.0) &
    (df_selected["pl_eqt"] >= 180) & (df_selected["pl_eqt"] <= 310)
).astype(int)

df_selected["habitable"].value_counts()

df_selected.head()

"""Save Final Clean Dataset"""

df_selected.to_csv("final_exoplanet_clean_dataset.csv", index=False)
print("Final cleaned dataset saved!")

"""Separate Features (X) and Target (y)"""

# Drop only the target column
X = df_selected.drop(columns=["habitable"])
y = df_selected["habitable"]

print("X shape:", X.shape)
print("y shape:", y.shape)

"""Train-Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

"""Feature Scaling (Standardization)"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""Check Final Prepared Dataset"""

print("Scaled Train shape:", X_train_scaled.shape)
print("Scaled Test shape:", X_test_scaled.shape)

"""Train Logistic Regression Model"""

from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

log_acc = log_model.score(X_test_scaled, y_test)
print("Logistic Regression Accuracy:", log_acc)

"""Train Random Forest Model"""

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model.fit(X_train, y_train)

rf_acc = rf_model.score(X_test, y_test)
print("Random Forest Accuracy:", rf_acc)

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

"""Train Support Vector Machine (SVM)"""

from sklearn.svm import SVC

svm_model = SVC(kernel="rbf")
svm_model.fit(X_train_scaled, y_train)

svm_acc = svm_model.score(X_test_scaled, y_test)
print("SVM Accuracy:", svm_acc)

"""Model Evaluation"""

from sklearn.metrics import classification_report, confusion_matrix

y_pred = rf_model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""Compare Model Accuracy"""

print("Logistic Regression:", log_acc)
print("Random Forest:", rf_acc)
print("SVM:", svm_acc)

"""Save Best Model (Random Forest)"""

import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Re-define selected_cols to ensure it's available
selected_cols = [
    "pl_rade",    # Planet radius
    "pl_bmasse",  # Planet mass
    "pl_orbper",  # Orbital period
    "pl_eqt",     # Equilibrium temperature
    "st_teff",    # Star temperature
    "st_mass",    # Star mass
    "st_rad",     # Star radius
    "sy_dist",    # System distance
    "pl_insol",   # Planet insolation flux
    "st_met"      # Star metallicity
]

# Re-load data and prepare X, y for training (as rf_model was trained on raw X, not scaled X_train_scaled)
# Assuming df and df_selected are available from previous steps, or re-create if needed.
# For robustness, let's assume df is available and re-create X, y, and scaler

# Load dataset
df = pd.read_csv("exoplanet_full_dataset.csv", comment="#", low_memory=False)
# Remove duplicates and fill NaNs based on previous notebook state
df = df.drop_duplicates()
df_selected = df[selected_cols].fillna(df[selected_cols].median())

X = df_selected.copy()
# Define target y
y = ((df_selected["pl_rade"] >= 0.5) & (df_selected["pl_rade"] <= 2.5) &
     (df_selected["pl_eqt"] >= 150) & (df_selected["pl_eqt"] <= 400)).astype(int)

# Train-test split not strictly needed for saving model, but for completeness or if model needs re-training
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Re-create and train rf_model (based on cell TWHufssvuzP7 content)
rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model.fit(X, y) # rf_model was trained on X (unscaled) in TWHufssvuzP7

# Re-create and fit scaler (based on cell 3_M6k6ADu0j content)
scaler = StandardScaler()
scaler.fit(X)

joblib.dump(rf_model, "habitability_model_10feat.pkl")
joblib.dump(scaler, "scaler_10feat.pkl")

print("Model saved successfully!")

"""Save 10 Feature Model"""

# -----------------------------
# Install libraries
# -----------------------------
!pip install pandas scikit-learn joblib matplotlib seaborn

# -----------------------------
# Imports
# -----------------------------
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
import joblib

# -----------------------------
# Load Dataset
# -----------------------------
df = pd.read_csv("exoplanet_full_dataset.csv", comment='#', low_memory=False)

# Keep 10 features that exist in the dataset
features = [ "pl_rade",    # Planet radius
    "pl_bmasse",  # Planet mass
    "pl_orbper",  # Orbital period
    "pl_eqt",     # Equilibrium temperature
    "st_teff",    # Star temperature
    "st_mass",    # Star mass
    "st_rad",     # Star radius
    "sy_dist",    # System distance
    "pl_insol",   # Planet insolation flux
    "st_met"      # Star metallicity
]
X = df[features]

# Create target 'habitable'
y = ((df["pl_rade"] >= 0.5) & (df["pl_rade"] <= 2.0) &
     (df["pl_eqt"] >= 180) & (df["pl_eqt"] <= 310)).astype(int)

# -----------------------------
# Scale features
# -----------------------------
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# -----------------------------
# Train model
# -----------------------------
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_scaled, y)

# -----------------------------
# Save scaler and model
# -----------------------------
joblib.dump(scaler, "scaler_10.pkl")
joblib.dump(model, "habitability_model_10.pkl")
print("10-feature model saved successfully!")

"""Flask Backend Code"""

from flask import Flask, request, jsonify
import joblib
import numpy as np

app = Flask(__name__)

# -----------------------------
# Load model and scaler
# -----------------------------
model = joblib.load("habitability_model_10.pkl")
scaler = joblib.load("scaler_10.pkl")

@app.route("/")
def home():
    return "Exoplanet Habitability Prediction API is running!"

@app.route("/predict", methods=["POST"])
def predict():
    data = request.json

    # Extract inputs (same order as training features)
    features = np.array([[
        data["pl_rade"],
        data["pl_bmasse"],
        data["pl_orbper"],
        data["pl_eqt"],
        data["st_teff"],
        data["st_mass"],
        data["st_rad"],
        data["sy_dist"],
        data["pl_insol"],
        data["st_met"]
    ]])

    # Scale features
    features_scaled = scaler.transform(features)

    # Prediction
    prediction = model.predict(features_scaled)[0]

    result = "Habitable ✅" if prediction == 1 else "Not Habitable ❌"

    return jsonify({"prediction": int(prediction), "result": result})

if __name__ == "__main__":
    app.run(debug=True)

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
import joblib

# Load dataset
df = pd.read_csv("exoplanet_full_dataset.csv", comment='#', low_memory=False)

# 10 features you want
features = ['pl_rade', 'pl_bmasse', 'pl_orbper', 'pl_eqt',
            'st_teff', 'st_mass', 'st_rad', 'sy_dist','pl_insol','st_met']
X = df[features]

# Target column
y = ((df["pl_rade"] >= 0.5) & (df["pl_rade"] <= 2.0) &
     (df["pl_eqt"] >= 180) & (df["pl_eqt"] <= 310)).astype(int)

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_scaled, y)

# Save 8-feature model & scaler
joblib.dump(scaler, "scaler_10feat.pkl")
joblib.dump(model, "habitability_model_10feat.pkl")
print("10-feature model & scaler saved!")

"""Test Model with 2 Different Data Inputs"""

import joblib
import numpy as np

# Load your 10-feature model & scaler
model = joblib.load("habitability_model_10feat.pkl")
scaler = joblib.load("scaler_10feat.pkl")

# -----------------------------
# Test Case 1: Example planet
data1 = np.array([[
    1.0,      # pl_rade
    1.0,      # pl_bmasse
    365.0,    # pl_orbper
    288.0,    # pl_eqt
    5778.0,   # st_teff
    1.0,      # st_mass
    1.0,      # st_rad
    10.0,     # sy_dist
    1361.0,   # pl_insol (Earth approx)
    0.0       # st_met (solar metallicity placeholder)
]])

# Test Case 2: Another example planet
data2 = np.array([[
    11.0,     # pl_rade
    300.0,    # pl_bmasse
    3.0,      # pl_orbper
    1500.0,   # pl_eqt
    6000.0,   # st_teff
    1.2,      # st_mass
    1.3,      # st_rad
    200.0,    # sy_dist
    5000.0,   # pl_insol
    0.1       # st_met
]])

# -----------------------------
# Scale the input data
data1_scaled = scaler.transform(data1)
data2_scaled = scaler.transform(data2)

# -----------------------------
# Make predictions
pred1 = model.predict(data1_scaled)
pred2 = model.predict(data2_scaled)

print("Test Case 1 Prediction:", "Habitable ✅" if pred1[0]==1 else "Not Habitable ❌")
print("Test Case 2 Prediction:", "Habitable ✅" if pred2[0]==1 else "Not Habitable ❌")

"""FINAL Flask Backend"""

from flask import Flask, request, jsonify
import joblib
import numpy as np

app = Flask(__name__)

# Load model and scaler
model = joblib.load("habitability_model_10feat.pkl")
scaler = joblib.load("scaler_10feat.pkl")

@app.route("/")
def home():
    return "Exoplanet Habitability Prediction API is Running!"

@app.route("/predict", methods=["POST"])
def predict():
    data = request.json

    # Get input values for the 8 features
    pl_rade = data["pl_rade"]
    pl_bmasse = data["pl_bmasse"]
    pl_orbper = data["pl_orbper"]
    pl_eqt = data["pl_eqt"]
    st_teff = data["st_teff"]
    st_mass = data["st_mass"]
    st_rad = data["st_rad"]
    sy_dist = data["sy_dist"]
    pl_insol=data["pl_insol"]
    st_met=data["st_met"]
    # Final input feature array (must match training order and number of features)
    features = np.array([[pl_rade, pl_bmasse, pl_orbper, pl_eqt,
                          st_teff, st_mass, st_rad, sy_dist,pl_insol.st_met]])

    # Scaling
    features_scaled = scaler.transform(features)

    # Prediction
    prediction = model.predict(features_scaled)[0]

    result = "Habitable" if prediction == 1 else "Not Habitable"

    return jsonify({
        "prediction": int(prediction),
        "result": result
    })

if __name__ == "__main__":
    app.run(debug=True)

from google.colab import files
files.download("habitability_model_10feat.pkl")
files.download("scaler_10feat.pkl")